language: php

php:
  - 7.4
  - 8.0
  - 8.1

before_script:
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost latest

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=.phpcs.xml src/
  - vendor/bin/phpstan analyse src/

notifications:
  email:
    recipients:
      - dev@buzzdeveloper.net
    on_success: never
    on_failure: always

branches:
  only:
    - main
    - develop